### ISSUE TITLE
Measurement Improvisation 

### ISSUE THREAD

**Issue by AIdeveloper-oz** [KimYC1223/3D-Body-Estimation#2]
Hi, Thanks for keeping this repo open. As far as observed, the measurements and body parts seem to be interrelated. Additionally, they seem to have a specific number of points to be deformed for each body part on reconstruction process. How could I alter the already available measurements or add new ones?

**Comment by KimYC1223** [comment]
Hello, @AIdeveloper-oz !

umm... you mean you want to add another parameter like "neck" , "chest" , "neck to gluteal hip" , etc ... ?

The body estimation program is generate body object based on learning data.

If you look at the [repo](https://github.com/1900zyh/3D-Human-Body-Shape) I used to create this project, it says to add datasets for training to the / data folder. (Download datasets [here](https://graphics.soe.ucsc.edu/data/BodyModels/index.html))

>![image](https://user-images.githubusercontent.com/40852277/76336841-ea18c900-6339-11ea-9e5e-6672ee42d47a.png)
>
>***Quoted in "Semantic Parametric Reshaping of Human Body Models"***

These datasets are based on the SCAPE Model. A detailed description of the SCAPE Model can be found [here](http://robots.stanford.edu/papers/anguelov.shapecomp.pdf) and [here](https://users.soe.ucsc.edu/~davis/papers/2014_3DV_SemanticBodyModels.pdf).

As far as I know, if you want to add other parameters, you won't be able to use the this SCAPE Model.

And... unfortunately, you don't use this SCAPE Model, you won't be able to use this training set & estimation program. _(because I didn't implement 'body estimation part', I don't know how to change 'model base' in this project. 😢 )_

I hope my answer was helpful.

I suggest to you visiting original reop and reading thesis.

bye.

**Comment by AIdeveloper-oz** [comment]
Hey Kim, Thanks for your quick response. It really adds more value for my research. I'm unable to find the complete version of the thesis for free. If you can share any link to the thesis, it would be more helpful.

**Comment by KimYC1223** [comment]
hi oz !!

![image](https://user-images.githubusercontent.com/40852277/76385090-284ad280-63a4-11ea-800f-f63e8f4ecf48.png)
 
You can access thesis by click hyperlink !

If you don't have access, please leave an email.

I will send you the file directly.

**Comment by AIdeveloper-oz** [comment]
That's so kind of you. Thanks Kim!!
